### ISSUE TITLE
Using BM25 and word embeddings throws division by zero error

### ISSUE THREAD

**Issue by ydennisy** [neuml/txtai#247]
Hello @davidmezzetti - thanks for a cool package.

I am having some issues using BM25, please see the sample below:

```python
from txtai.embeddings import Embeddings

embeddings = Embeddings({
    "path": "GoogleNews-vectors-negative300.magnitude",
    "scoring": "bm25",
})

embeddings.index(
    [(uid, text, None) for uid, text in enumerate(docs)])
```

Will create the following error:

```
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/dennisyurkevich/.pyenv/versions/3.7.8/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/Users/dennisyurkevich/.pyenv/versions/3.7.8/lib/python3.7/site-packages/txtai/vectors/words.py", line 57, in transform
    return (document[0], VECTORS.transform(document))
  File "/Users/dennisyurkevich/.pyenv/versions/3.7.8/lib/python3.7/site-packages/txtai/vectors/words.py", line 129, in transform
    weights = self.scoring.weights(document) if self.scoring else None
  File "/Users/dennisyurkevich/.pyenv/versions/3.7.8/lib/python3.7/site-packages/txtai/scoring/base.py", line 112, in weights
    weights.append(self.score(freq, idf, length))
  File "/Users/dennisyurkevich/.pyenv/versions/3.7.8/lib/python3.7/site-packages/txtai/scoring/bm25.py", line 29, in score
    k = self.k1 * ((1 - self.b) + self.b * length / self.avgdl)
ZeroDivisionError: float division by zero
"""

The above exception was the direct cause of the following exception:

ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-29-b4da4f34aa72> in <module>
      7 
      8 embeddings.index(
----> 9     [(uid, text, None) for uid, text in enumerate(docs)])
     10 
     11 

~/.pyenv/versions/3.7.8/lib/python3.7/site-packages/txtai/embeddings/base.py in index(self, documents, reindex)
     94         with tempfile.NamedTemporaryFile(mode="wb", suffix=".npy") as buffer:
     95             # Load documents into database and transform to vectors
---> 96             ids, dimensions, embeddings = transform(documents, buffer)
     97             if ids:
     98                 # Build LSA model (if enabled). Remove principal components from embeddings.

~/.pyenv/versions/3.7.8/lib/python3.7/site-packages/txtai/embeddings/transform.py in __call__(self, documents, buffer)
     55 
     56         # Transform documents to vectors and load into database
---> 57         ids, dimensions, batches, stream = self.model.index(self.stream(documents))
     58 
     59         # Check that embeddings are available and load as a memmap

~/.pyenv/versions/3.7.8/lib/python3.7/site-packages/txtai/vectors/words.py in index(self, documents)
    111             with tempfile.NamedTemporaryFile(mode="wb", suffix=".npy", delete=False) as output:
    112                 stream = output.name
--> 113                 for uid, embedding in pool.imap(transform, documents):
    114                     if not dimensions:
    115                         # Set number of dimensions for embeddings

~/.pyenv/versions/3.7.8/lib/python3.7/multiprocessing/pool.py in next(self, timeout)
    746         if success:
    747             return value
--> 748         raise value
    749 
    750     __next__ = next                    # XXX

ZeroDivisionError: float division by zero
```

Removing `bm25` from scoring will resolve the issue.

**Comment by davidmezzetti** [comment]
Hello, thanks for reaching out and the nice words on txtai. 

I've [updated the documentation](https://neuml.github.io/txtai/embeddings/#scoring) to clarify this - word vector models require building the scoring index (in this case bm25) before the embeddings index. 

For example:

```python
from txtai.embeddings import Embeddings

embeddings = Embeddings({
    "path": "GoogleNews-vectors-negative300.magnitude",
    "scoring": "bm25",
})

# This line added to build the scoring index
embeddings.score(
    [(uid, text, None) for uid, text in enumerate(docs)])

embeddings.index(
    [(uid, text, None) for uid, text in enumerate(docs)])
```

**Comment by ydennisy** [comment]
Thanks @davidmezzetti all good now!
