### ISSUE TITLE
  asyncio.exceptions.TimeoutError when running 'cluster.add(docs)  cluster.index()'

### ISSUE THREAD

**Issue by wspspring** [neuml/txtai#260]
Traceback (most recent call last):
  File "run.py", line 58, in <module>
    cluster.index()
  File "/root/miniconda3/envs/txtai/lib/python3.8/site-packages/txtai/api/cluster.py", line 118, in index
    self.execute("get", "index")
  File "/root/miniconda3/envs/txtai/lib/python3.8/site-packages/txtai/api/cluster.py", line 197, in execute
    return loop.run_until_complete(self.run(urls, method, data))
  File "/root/miniconda3/envs/txtai/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/root/miniconda3/envs/txtai/lib/python3.8/site-packages/txtai/api/cluster.py", line 226, in run
    return await asyncio.gather(*tasks)
  File "/root/miniconda3/envs/txtai/lib/python3.8/site-packages/txtai/api/cluster.py", line 240, in get
    async with session.get(url) as resp:
  File "/root/miniconda3/envs/txtai/lib/python3.8/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/root/miniconda3/envs/txtai/lib/python3.8/site-packages/aiohttp/client.py", line 559, in _request
    await resp.start(conn)
  File "/root/miniconda3/envs/txtai/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 913, in start
    self._continue = None
  File "/root/miniconda3/envs/txtai/lib/python3.8/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError

**Comment by davidmezzetti** [comment]
Thank you for submitting the issue. 

Is there more information or configuration you can provide? I am not sure how to reproduce this issue.

**Comment by davidmezzetti** [comment]
Closing due to inactivity. Feel free to reach back out if there are further questions.
