### ISSUE TITLE
Unable to start the API server because of a TypeError

### ISSUE THREAD

**Issue by dush-t** [neuml/txtai#411]
When I try to start the API server, I get the following error - 
```
CONFIG=app.yml uvicorn "txtai.api:app" --host 0.0.0.0
INFO:     Started server process [34703]
INFO:     Waiting for application startup.
ERROR:    Traceback (most recent call last):
  File "/Users/dushyant/Projects/blaze-env/lib/python3.9/site-packages/starlette/routing.py", line 671, in lifespan
    async with self.lifespan_context(app):
  File "/Users/dushyant/Projects/blaze-env/lib/python3.9/site-packages/starlette/routing.py", line 566, in __aenter__
    await self._router.startup()
  File "/Users/dushyant/Projects/blaze-env/lib/python3.9/site-packages/starlette/routing.py", line 650, in startup
    handler()
  File "/Users/dushyant/Projects/blaze-env/lib/python3.9/site-packages/txtai/api/application.py", line 67, in start
    INSTANCE = Factory.create(config, api) if api else API(config)
  File "/Users/dushyant/Projects/blaze-env/lib/python3.9/site-packages/txtai/api/base.py", line 18, in __init__
    super().__init__(config, loaddata)
  File "/Users/dushyant/Projects/blaze-env/lib/python3.9/site-packages/txtai/app/base.py", line 67, in __init__
    self.pipes()
  File "/Users/dushyant/Projects/blaze-env/lib/python3.9/site-packages/txtai/app/base.py", line 103, in pipes
    config = self.config[pipeline] if self.config[pipeline] else {}
TypeError: string indices must be integers

ERROR:    Application startup failed. Exiting
```

My config file looks like this - 
```
# app.yml
embeddings:
    path: sentence-transformers/all-MiniLM-L6-v2
```

I'm using Python 3.9

Am I missing something here?

**Comment by davidmezzetti** [comment]
Are you sure app.yml is in the current directory? While the error is not clear (#412 will fix that), it happens when the config file is not found.

**Comment by davidmezzetti** [comment]
Closing due to inactivity. Please open a new issue or re-open this issue if this persists.
