### ISSUE TITLE
Receiving "install "cloud" extra to enable" when trying to load from S3? v5.6.0

### ISSUE THREAD

**Issue by jridevapp** [neuml/txtai#466]

**Comment by jridevapp** [comment]
Ah, nevermind, just saw the txtai[cloud], got that installed but now getting this error:

embeddings.load(provider="s3", container="folder/here", key=ACCESS_KEY, secret=SECRET_KEY, host="s3.us-east-1.amazonaws.com", region="us-east-1")

   os.makedirs(path, exist_ok=True)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/os.py", line 210, in makedirs
    head, tail = path.split(name)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/posixpath.py", line 103, in split
    p = os.fspath(p)

**Comment by jridevapp** [comment]
Tried on 3.9 seeing the same error...

**Comment by jridevapp** [comment]
```
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/appd/Documents/AA/app-1/txtai/.venv/lib/python3.9/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/Users/appd/Documents/AA/app-1/txtai/.venv/lib/python3.9/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/appd/Documents/AA/app-1/txtai/.venv/lib/python3.9/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/Users/appd/Documents/AA/app-1/txtai/.venv/lib/python3.9/site-packages/uvicorn/config.py", line 477, in load
    self.loaded_app = import_from_string(self.app)
  File "/Users/appd/Documents/AA/app-1/txtai/.venv/lib/python3.9/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/local/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/appd/Documents/AA/app-1/txtai/./main.py", line 60, in <module>
    embeddings.load(provider="s3", container="txtai-api/volumes", key=ACCESS_KEY, secret=SECRET_KEY, host="s3.us-east-1.amazonaws.com", region="us-east-1")
  File "/Users/appd/Documents/AA/app-1/txtai/.venv/lib/python3.9/site-packages/txtai/embeddings/base.py", line 483, in load
    path = cloud.load(path)
  File "/Users/appd/Documents/AA/app-1/txtai/.venv/lib/python3.9/site-packages/txtai/cloud/storage.py", line 78, in load
    os.makedirs(path, exist_ok=True)
  File "/usr/local/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/os.py", line 210, in makedirs
    head, tail = path.split(name)
  File "/usr/local/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/posixpath.py", line 103, in split
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by davidmezzetti** [comment]
This is now noted in the documentation: 

https://neuml.github.io/txtai/embeddings/configuration/cloud/#container
https://neuml.github.io/txtai/embeddings/methods/#txtai.embeddings.base.Embeddings.load

Closing.
