### ISSUE TITLE
embeddings.upsert() to qdrant failure

### ISSUE THREAD

**Issue by fossapp** [neuml/txtai#479]
Good morning,

embeddings.upsert() fails with the following error while trying to upsert a vector into qdrant

**self.cursor.execute(FileDB.INSERT_SECTION, [index, uid, text, tags, entry])
sqlite3.OperationalError: database is locked**

the code used for upsert was:

**embeddings.upsert([(vectorID, text, None) for vectorID, text in enumerate(data_list)])**

Same vector can be added without error using embeddings.index([(vectorID, text, None) for vectorID, text in enumerate(data_list)]), however the existing index gets deleted and a new index containing only the new vector is created.

Your help will be much appreciated!

Thank you

---

Here is the detailed error message:

INFO:     127.0.0.1:48596 - "POST /upxml HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/venvlib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/venvlib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/venvlib/python3.10/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/venvlib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/venvlib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/venvlib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/venvlib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/venvlib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/venvlib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/venvlib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/venvlib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/venvlib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/venvlib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/venvlib/python3.10/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/venvlib/python3.10/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "/app/routers/upxml.py", line 56, in post_form
    embeddings.upsert([(vectorID, text, None) for vectorID, text in enumerate(data_list)])
  File "/venvlib/python3.10/site-packages/txtai/embeddings/base.py", line 167, in upsert
    ids, _, embeddings = transform(documents, buffer)
  File "/venvlib/python3.10/site-packages/txtai/embeddings/transform.py", line 58, in __call__
    ids, dimensions, batches, stream = self.model.index(self.stream(documents), self.batch)
  File "/venvlib/python3.10/site-packages/txtai/vectors/base.py", line 84, in index
    for document in documents:
  File "/venvlib/python3.10/site-packages/txtai/embeddings/transform.py", line 117, in stream
    self.load(batch, offset)
  File "/venvlib/python3.10/site-packages/txtai/embeddings/transform.py", line 142, in load
    self.database.insert(batch, self.offset)
  File "/venvlib/python3.10/site-packages/txtai/database/filedb.py", line 150, in insert
    self.insertsection(index, uid, document, tags, entry)
  File "/venvlib/python3.10/site-packages/txtai/database/filedb.py", line 418, in insertsection
    **self.cursor.execute(FileDB.INSERT_SECTION, [index, uid, text, tags, entry])
sqlite3.OperationalError: database is locked**

**Comment by thtran02** [comment]
I don't know how to resolve the database locking issue, but if you upsert with enumerate, vectorID will start at 0 each time and your existing index with vectorID in range(0, len(data_list)) will get overwritten. Perhaps use uuid for the vectorID?

import uuid
embeddings.upsert([(str(uuid.uuid4()), text, None) for text in data_list])

**Comment by davidmezzetti** [comment]
It appears you're running in a multi-request environment (FastAPI is in the stack trace). You should consider using an application instance instead. Or reproduce the locking code found [in this file](https://github.com/neuml/txtai/blob/master/src/python/txtai/app/base.py) in your router (upxml.py).

**Comment by fossapp** [comment]
Thank you all for your suggestions! I am running an app instance app = FastAPI() with a router /upxml  which works fine with embeddings.indext() and fails while trying to use embeddings.upsert(), instead.

**Comment by fossapp** [comment]
Managed to get the upsert method to insert a vector in qdrant database by using the following syntax embeddings.upsert([(key, string_data, None)]). Unfortunately the index gets recreated as in the case of embeddings.index() and I end up with one vector in qdrant database and the index.

Wondering whether there is a way to add one vector to an existing index.

**Comment by davidmezzetti** [comment]
As @thtran02 mentioned above, if the unique id is repeated, records will be overwritten. For example if `key` is the same `key` as was used in the `index` call, it will replace the existing entry.

**Comment by davidmezzetti** [comment]
Close this due to inactivity. Please re-open and open a new issue to continue the conversation.
