### ISSUE TITLE
All examples error

### ISSUE THREAD

**Issue by vanhauser-thc** [neuml/txtai#483]
I am using `Python 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0] on linux`

I created a virtual environment and installed `pip install txtai[all]` however I also needed to install `pip install streamlit` as this is not part of `all`.

Running any of the example fail, e.g.:
```
(.venv) /prg/tmp/txtai (master) # python examples/article.py 
/prg/tmp/txtai/.venv/lib/python3.11/site-packages/skl2onnx/algebra/onnx_ops.py:159: UserWarning: OpSchema.FormalParameter.typeStr is deprecated and will be removed in 1.16. Use OpSchema.FormalParameter.type_str instead.
  tys = obj.typeStr or ''
/prg/tmp/txtai/.venv/lib/python3.11/site-packages/skl2onnx/algebra/automation.py:154: UserWarning: OpSchema.FormalParameter.isHomogeneous is deprecated and will be removed in 1.16. Use OpSchema.FormalParameter.is_homogeneous instead.
  if getattr(obj, 'isHomogeneous', False):
/prg/tmp/txtai/.venv/lib/python3.11/site-packages/jinja2/environment.py:485: UserWarning: OpSchema.FormalParameter.typeStr is deprecated and will be removed in 1.16. Use OpSchema.FormalParameter.type_str instead.
  return getattr(obj, attribute)
2023-06-05 09:57:26.737 
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run examples/article.py [ARGUMENTS]
Traceback (most recent call last):
  File "/prg/tmp/txtai/.venv/lib/python3.11/site-packages/streamlit/runtime/legacy_caching/caching.py", line 678, in get_or_create_cached_value
    return_value = _read_from_cache(
                   ^^^^^^^^^^^^^^^^^
  File "/prg/tmp/txtai/.venv/lib/python3.11/site-packages/streamlit/runtime/legacy_caching/caching.py", line 435, in _read_from_cache
    raise e
  File "/prg/tmp/txtai/.venv/lib/python3.11/site-packages/streamlit/runtime/legacy_caching/caching.py", line 420, in _read_from_cache
    return _read_from_mem_cache(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/prg/tmp/txtai/.venv/lib/python3.11/site-packages/streamlit/runtime/legacy_caching/caching.py", line 337, in _read_from_mem_cache
    raise CacheKeyNotFoundError("Key not found in mem cache")
streamlit.runtime.legacy_caching.caching.CacheKeyNotFoundError: Key not found in mem cache

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/prg/tmp/txtai/examples/article.py", line 65, in <module>
    app = create()
          ^^^^^^^^
  File "/prg/tmp/txtai/.venv/lib/python3.11/site-packages/streamlit/runtime/legacy_caching/caching.py", line 715, in wrapped_func
    return get_or_create_cached_value()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/prg/tmp/txtai/.venv/lib/python3.11/site-packages/streamlit/runtime/legacy_caching/caching.py", line 696, in get_or_create_cached_value
    return_value = non_optional_func(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/prg/tmp/txtai/examples/article.py", line 58, in create
    return Application()
           ^^^^^^^^^^^^^
  File "/prg/tmp/txtai/examples/article.py", line 27, in __init__
    summary = Summary("sshleifer/distilbart-cnn-12-6")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/prg/tmp/txtai/.venv/lib/python3.11/site-packages/txtai/pipeline/text/summary.py", line 16, in __init__
    super().__init__("summarization", path, quantize, gpu, model)
  File "/prg/tmp/txtai/.venv/lib/python3.11/site-packages/txtai/pipeline/hfpipeline.py", line 44, in __init__
    self.pipeline = pipeline(task, model=path, device=deviceid)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/prg/tmp/txtai/.venv/lib/python3.11/site-packages/transformers/pipelines/__init__.py", line 788, in pipeline
    framework, model = infer_framework_load_model(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/prg/tmp/txtai/.venv/lib/python3.11/site-packages/transformers/pipelines/base.py", line 279, in infer_framework_load_model
    raise ValueError(f"Could not load model {model} with any of the following classes: {class_tuple}.")
ValueError: Could not load model sshleifer/distilbart-cnn-12-6 with any of the following classes: (<class 'transformers.models.auto.modeling_auto.AutoModelForSeq2SeqLM'>, <class 'transformers.models.bart.modeling_bart.BartForConditionalGeneration'>).
```

the main error in the examples seeming to be:
```
File "/prg/tmp/txtai/.venv/lib/python3.11/site-packages/streamlit/runtime/legacy_caching/caching.py", line 337, in _read_from_mem_cache
    raise CacheKeyNotFoundError("Key not found in mem cache")
```

how can I fix this? thanks!

**Comment by vanhauser-thc** [comment]
ok the problem was that I cloned the repository sshleifer/distilbart-cnn-12-6 into the txtai so the download in the python script seem to fail.
