### ISSUE TITLE
ValueError: dictionary update sequence element #0 has length X; 2 is required

### ISSUE THREAD

**Issue by Vincent-liuwingsang** [neuml/txtai#529]
I've been getting this error since upgrading to v6. Any idea what this could me?🤔

```
Embeddings(
        {
            "method": "sentence-transformers",
            "path": "sentence-transformers/all-MiniLM-L6-v2",
            "content": "src.custom_sqlite.sqlite.SQLite",
            "hybrid": True,
        }
    )
```

```
failed to process screenshots Traceback (most recent call last):
  File "/Users/wingsangvincentliu/Pathless/unlost-server/src/process_screenshots.py", line 29, in process_screenshots
    if process_screenshots_inner():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/wingsangvincentliu/Pathless/unlost-server/src/process_screenshots.py", line 115, in process_screenshots_inner
    store_memory.persist()
  File "/Users/wingsangvincentliu/Pathless/unlost-server/src/memory.py", line 232, in persist
    embedding.instance.upsert(docs)
  File "/Users/wingsangvincentliu/.pyenv/versions/3.11.1/lib/python3.11/site-packages/txtai/embeddings/base.py", line 174, in upsert
    ids, _, embeddings = transform(stream(documents), buffer)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/wingsangvincentliu/.pyenv/versions/3.11.1/lib/python3.11/site-packages/txtai/embeddings/index/transform.py", line 72, in __call__
    ids, dimensions, embeddings = self.vectors(documents, buffer)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/wingsangvincentliu/.pyenv/versions/3.11.1/lib/python3.11/site-packages/txtai/embeddings/index/transform.py", line 91, in vectors
    ids, dimensions, batches, stream = self.model.index(self.stream(documents), self.batch)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/wingsangvincentliu/.pyenv/versions/3.11.1/lib/python3.11/site-packages/txtai/vectors/base.py", line 92, in index
    for document in documents:
  File "/Users/wingsangvincentliu/.pyenv/versions/3.11.1/lib/python3.11/site-packages/txtai/embeddings/index/transform.py", line 170, in stream
    self.load(batch, offset)
  File "/Users/wingsangvincentliu/.pyenv/versions/3.11.1/lib/python3.11/site-packages/txtai/embeddings/index/transform.py", line 204, in load
    self.scoring.insert(batch, self.offset)
  File "/Users/wingsangvincentliu/.pyenv/versions/3.11.1/lib/python3.11/site-packages/txtai/scoring/base.py", line 104, in insert
    self.addstats(tokens, tags)
  File "/Users/wingsangvincentliu/.pyenv/versions/3.11.1/lib/python3.11/site-packages/txtai/scoring/base.py", line 398, in addstats
    self.tags.update(tags.split())
ValueError: dictionary update sequence element #0 has length 15; 2 is required
```

**Comment by Vincent-liuwingsang** [comment]
looks like it could be related to improperly formatted tags string. Current input is a json serialised string for tags

**Comment by davidmezzetti** [comment]
Can you share the type of data you're trying to put into the tags field? Not sure why that line would give that error if tags is a string.

**Comment by davidmezzetti** [comment]
Ok, I'll see what is going on and handle the error.

But I wouldn't recommend using tags the way you are. It's designed for a simple list of space separated strings. It's better to put this data in the document JSON. And with that, I wouldn't put it as a string but as a dict so these fields become searchable and selectable.

**Comment by Vincent-liuwingsang** [comment]
thanks!

Where should I put them if I don't want the data to be searchable?

**Comment by davidmezzetti** [comment]
Just store it as a string in the JSON, that's the best option.

**Comment by Vincent-liuwingsang** [comment]
What effects do tags have on search result? I see some code around it in scoring for weights.

**Comment by davidmezzetti** [comment]
Sorry for the delayed response on this. The tags field isn't used with terms scoring.

**Comment by Vincent-liuwingsang** [comment]
No worries and thanks. I'm happy to close this as I've gone with your suggestions

**Comment by davidmezzetti** [comment]
I'll keep this one open as it still looks like something should be handled better in this situation.
