### ISSUE TITLE
Issues with workers and concurrency

### ISSUE THREAD

**Issue by ak4hcl** [neuml/txtai#580]
txtai's search and document training is working well with its default configuration and single instance. In case of scaling the application and concurrency, it lacks something. I tried enabling 4 workers to improve search performance with following txtai config but I was not able to achieve what I was looking for. With multiple-workers search is not providing results for some requests and upsert operation is failing with error code 500 saying db lock issue from sqlite. I tried another approach by integrating postgres database with txtai's latest version. With postgres and 4 workers there are no db lock errors but rarely it sometimes gives empty results(inconsistent) for some requests when I tried testing search performance with jmeter. 

In short, I tried various supported configuration like default, sqlite wal, postgres but didn't get any improvement, instead there are different errors I am getting.
```
# Index file path
path: ./index
# Allow indexing of documents
writable: True

# Enbeddings index
embeddings:
  path: sentence-transformers/all-MiniLM-L6-v2
  content: True
  hybrid: True
```
Error log
```
$ CONFIG=hybridindex.yml uvicorn --host 0.0.0.0 --port 8000 --workers 4 "txtai.api:app"
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Started parent process [19436]
INFO:     Started server process [9160]
INFO:     Waiting for application startup.
INFO:     Started server process [23868]
INFO:     Waiting for application startup.
INFO:     Started server process [16436]
INFO:     Waiting for application startup.
INFO:     Started server process [25512]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Application startup complete.
INFO:     Application startup complete.
INFO:     Application startup complete.
INFO:     127.0.0.1:50088 - "POST /batchsearch HTTP/1.1" 200 OK
INFO:     127.0.0.1:50092 - "POST /batchsearch HTTP/1.1" 200 OK
INFO:     127.0.0.1:50097 - "POST /batchsearch HTTP/1.1" 200 OK
INFO:     127.0.0.1:50102 - "POST /batchsearch HTTP/1.1" 200 OK
INFO:     127.0.0.1:50145 - "POST /batchsearch HTTP/1.1" 200 OK
INFO:     127.0.0.1:50145 - "POST /batchsearch HTTP/1.1" 200 OK
INFO:     127.0.0.1:50145 - "POST /delete HTTP/1.1" 200 OK
INFO:     127.0.0.1:50155 - "POST /add HTTP/1.1" 200 OK
INFO:     127.0.0.1:50155 - "GET /upsert HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\sakash\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\sakash\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\sakash\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\applications.py", line 289, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\sakash\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\sakash\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\sakash\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\sakash\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\Users\sakash\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\sakash\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "C:\Users\sakash\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\sakash\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\sakash\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "C:\Users\sakash\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "C:\Users\sakash\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\routing.py", line 273, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\sakash\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\routing.py", line 192, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "C:\Users\sakash\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "C:\Users\sakash\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\sakash\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\sakash\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\sakash\AppData\Local\Programs\Python\Python310\lib\site-packages\txtai\api\routers\embeddings.py", line 88, in upsert
    application.get().upsert()
  File "C:\Users\sakash\AppData\Local\Programs\Python\Python310\lib\site-packages\txtai\api\base.py", line 82, in upsert
    super().upsert()
  File "C:\Users\sakash\AppData\Local\Programs\Python\Python310\lib\site-packages\txtai\app\base.py", line 412, in upsert
    self.embeddings.save(self.config["path"], self.config.get("cloud"))
  File "C:\Users\sakash\AppData\Local\Programs\Python\Python310\lib\site-packages\txtai\embeddings\base.py", line 614, in save
    self.database.save(f"{path}/documents")
  File "C:\Users\sakash\AppData\Local\Programs\Python\Python310\lib\site-packages\txtai\database\embedded.py", line 55, in save
    self.connection.commit()
sqlite3.OperationalError: database is locked
```

As it looks like when search and upsert happens at the same time db lock issue is there with sqlite, I tried sqlite wal configuration. But again some errors I was facing when tried with multiple workers as follows,
```
# Index file path
path: ./hybridindexsql
# Allow indexing of documents
writable: True
# Enbeddings index
embeddings:
  path: sentence-transformers/all-MiniLM-L6-v2
  content: sqlite
  sqlite:
    wal: True
  hybrid: True
```
1.
```
INFO:     127.0.0.1:53578 - "POST /batchsearch HTTP/1.1" 200 OK
INFO:     127.0.0.1:53495 - "POST /batchsearch HTTP/1.1" 200 OK
INFO:     127.0.0.1:53500 - "POST /delete HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\sakash\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\sakash\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\sakash\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\applications.py", line 289, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\sakash\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\sakash\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\sakash\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\sakash\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\Users\sakash\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\sakash\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "C:\Users\sakash\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\sakash\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\sakash\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "C:\Users\sakash\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "C:\Users\sakash\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\routing.py", line 273, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\sakash\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\routing.py", line 192, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "C:\Users\sakash\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "C:\Users\sakash\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\sakash\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\sakash\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\sakash\AppData\Local\Programs\Python\Python310\lib\site-packages\txtai\api\routers\embeddings.py", line 106, in delete
    return application.get().delete(ids)
  File "C:\Users\sakash\AppData\Local\Programs\Python\Python310\lib\site-packages\txtai\api\base.py", line 98, in delete
    return super().delete(ids)
  File "C:\Users\sakash\AppData\Local\Programs\Python\Python310\lib\site-packages\txtai\app\base.py", line 435, in delete
    return self.embeddings.delete(ids)
  File "C:\Users\sakash\AppData\Local\Programs\Python\Python310\lib\site-packages\txtai\embeddings\base.py", line 229, in delete
    self.database.delete(deletes)
  File "C:\Users\sakash\AppData\Local\Programs\Python\Python310\lib\site-packages\txtai\database\rdbms.py", line 78, in delete
    self.cursor.execute(Statement.DELETE_DOCUMENTS)
sqlite3.OperationalError: database is locked
INFO:     127.0.0.1:53551 - "POST /batchsearch HTTP/1.1" 200 OK
INFO:     127.0.0.1:53511 - "POST /batchsearch HTTP/1.1" 200 OK
```
2.
```
INFO:     10.46.0.6:46862 - "POST /add HTTP/1.1" 200 OK
INFO:     10.46.0.6:46862 - "GET /upsert HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/applications.py", line 292, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/usr/local/lib/python3.8/dist-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 192, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.8/dist-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/usr/local/lib/python3.8/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.8/dist-packages/txtai/api/routers/embeddings.py", line 88, in upsert
    application.get().upsert()
  File "/usr/local/lib/python3.8/dist-packages/txtai/api/base.py", line 82, in upsert
    super().upsert()
  File "/usr/local/lib/python3.8/dist-packages/txtai/app/base.py", line 412, in upsert
    self.embeddings.save(self.config["path"], self.config.get("cloud"))
  File "/usr/local/lib/python3.8/dist-packages/txtai/embeddings/base.py", line 614, in save
    self.database.save(f"{path}/documents")
  File "/usr/local/lib/python3.8/dist-packages/txtai/database/embedded.py", line 40, in save
    connection = self.copy(path)
  File "/usr/local/lib/python3.8/dist-packages/txtai/database/sqlite.py", line 55, in copy
    self.connection.backup(connection)
sqlite3.OperationalError: disk I/O error
INFO:     10.46.0.6:46870 - "POST /add HTTP/1.1" 200 OK
```
3.
```
IndexError: index 13 is out of bounds for axis 0 with size 13
INFO:     10.244.2.114:41636 - "POST /batchsearch HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/applications.py", line 292, in __call__        
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/applications.py", line 122, in __call__      
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 184, in __call__ 
    raise exc
...
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/usr/local/lib/python3.8/dist-packages/txtai/scoring/base.py", line 230, in search
    scores = self.terms.search(query, limit)
  File "/usr/local/lib/python3.8/dist-packages/txtai/scoring/terms.py", line 180, in search
    uids, weights = self.weights(term)
  File "/usr/local/lib/python3.8/dist-packages/txtai/scoring/terms.py", line 416, in weights
    weights = self.score(np.frombuffer(freqs, dtype=np.int64), self.idf[term], lengths[uids]).astype(np.float32)
```

postgres: (tried following config with multi-workers, it worked without db lock issue, I could see the contents in postgres db directly also, but sometimes txtai gives empty response for search)
```
embeddings:
  path: sentence-transformers/all-MiniLM-L6-v2
  content: postgresql+psycopg2://postgres:postgres@localhost/postgres
  hybrid: True
```
Any help, fix or workaround is much appreciated. Thank you.

**Comment by davidmezzetti** [comment]
Are you planning to run your production environment on Windows? If you are planning to ultimately run on a Linux environment, might be better to test in that environment. While Windows is supported, I don't run txtai on Windows outside of the build scripts.

**Comment by ak4hcl** [comment]
The plan is to use txtai with docker only. But it doesn't seem that production friendly especially for scaling. I tried using gunicorn also with docker and linux. The problem I am facing is.. let's say I enabled 4 workers and started txtai like below,
```
docker logs --follow 209
[2023-10-19 07:15:17 +0000] [1] [INFO] Starting gunicorn 21.2.0
[2023-10-19 07:15:17 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000/ (1)
[2023-10-19 07:15:17 +0000] [1] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2023-10-19 07:15:17 +0000] [8] [INFO] Booting worker with pid: 8
[2023-10-19 07:15:17 +0000] [20] [INFO] Booting worker with pid: 20
[2023-10-19 07:15:17 +0000] [21] [INFO] Booting worker with pid: 21
[2023-10-19 07:15:17 +0000] [22] [INFO] Booting worker with pid: 22
[2023-10-19 07:15:22 +0000] [21] [INFO] Started server process [21]
[2023-10-19 07:15:22 +0000] [21] [INFO] Waiting for application startup.
[2023-10-19 07:15:22 +0000] [8] [INFO] Started server process [8]
[2023-10-19 07:15:22 +0000] [8] [INFO] Waiting for application startup.
[2023-10-19 07:15:22 +0000] [22] [INFO] Started server process [22]
[2023-10-19 07:15:22 +0000] [22] [INFO] Waiting for application startup.
[2023-10-19 07:15:22 +0000] [20] [INFO] Started server process [20]
[2023-10-19 07:15:22 +0000] [20] [INFO] Waiting for application startup.
[2023-10-19 07:15:24 +0000] [8] [INFO] Application startup complete.
[2023-10-19 07:15:24 +0000] [20] [INFO] Application startup complete.
[2023-10-19 07:15:24 +0000] [21] [INFO] Application startup complete.
[2023-10-19 07:15:24 +0000] [22] [INFO] Application startup complete. 
```
Now, I do one /add and /upsert. This data training is going to one instance of the txtai among the 4. When I do /search with some query related to the content I have trained, I am getting results for the first time. Then I call /search again with same query, this time I am getting empty result. Problem is like only one instance have the data, not all the 4 instances. I hit /search for the 3rd time now I am getting results. Same thing is happening when we have txtai as multi-pods also.

Not sure, but I think txtai is tightly coupled with sqlite(or any other db). There should be one single sqlite database centralized, so that we can have multiple txtai instances either with multiple pods or workers. That way maybe we can read/write content from any of the instances.

**Comment by davidmezzetti** [comment]
If you want to scale txtai out, here are some links to review:

- https://neuml.github.io/txtai/api/cluster/
- https://neuml.github.io/txtai/examples/#scale

The cluster interface is how one would scale out a txtai instance vs unicorn workers/concurrency. This also creates separate processes to scale out but it has a single controller process to prevent the types of issues your seeing.

**Comment by davidmezzetti** [comment]
Closing this due to inactivity. Please re-open or open a new issue if there are further questions.
