### ISSUE TITLE
gguf does not work neither from path nor from HF repo

### ISSUE THREAD

**Issue by ciekawy** [neuml/txtai#617]
also I tried both `method="llama.cpp"` and without.

trying LLM from local path gives:
```
Traceback (most recent call last):
  File "/Users/szymon/git/my-first-llm-rag/query.py", line 7, in <module>
    llm = LLM("/Volumes/ciekaDrive/models/mistral-7b-instruct-v0.2.Q6_K.gguf", method="llama.cpp", verbose=True)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/myenv/lib/python3.11/site-packages/txtai/pipeline/text/llm.py", line 18, in __init__
    super().__init__(self.task(path, task, **kwargs), path if path else "google/flan-t5-base", quantize, gpu, model, **kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/myenv/lib/python3.11/site-packages/txtai/pipeline/text/llm.py", line 103, in task
    task = Models.task(path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/myenv/lib/python3.11/site-packages/txtai/models/models.py", line 239, in task
    config = AutoConfig.from_pretrained(path, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/myenv/lib/python3.11/site-packages/transformers/models/auto/configuration_auto.py", line 1082, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/myenv/lib/python3.11/site-packages/transformers/configuration_utils.py", line 644, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/myenv/lib/python3.11/site-packages/transformers/configuration_utils.py", line 732, in _get_config_dict
    raise EnvironmentError(
OSError: It looks like the config file at '/Volumes/ciekaDrive/models/mistral-7b-instruct-v0.2.Q6_K.gguf' is not a valid JSON file.
```

and from the repo:

```
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/myenv/lib/python3.11/site-packages/transformers/utils/hub.py", line 389, in cached_file
    resolved_file = hf_hub_download(
                    ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/myenv/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 110, in _inner_fn
    validate_repo_id(arg_value)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/myenv/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 158, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 'TheBloke/Mistral-7B-Instruct-v0.2-GGUF/mistral-7b-instruct-v0.2.Q6_K.gguf'. Use `repo_type` argument if needed.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/szymon/git/my-first-llm-rag/query.py", line 7, in <module>
    llm = LLM("TheBloke/Mistral-7B-Instruct-v0.2-GGUF/mistral-7b-instruct-v0.2.Q6_K.gguf", method="llama.cpp", verbose=True)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/myenv/lib/python3.11/site-packages/txtai/pipeline/text/llm.py", line 18, in __init__
    super().__init__(self.task(path, task, **kwargs), path if path else "google/flan-t5-base", quantize, gpu, model, **kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/myenv/lib/python3.11/site-packages/txtai/pipeline/text/llm.py", line 103, in task
    task = Models.task(path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/myenv/lib/python3.11/site-packages/txtai/models/models.py", line 239, in task
    config = AutoConfig.from_pretrained(path, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/myenv/lib/python3.11/site-packages/transformers/models/auto/configuration_auto.py", line 1082, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/myenv/lib/python3.11/site-packages/transformers/configuration_utils.py", line 644, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/myenv/lib/python3.11/site-packages/transformers/configuration_utils.py", line 699, in _get_config_dict
    resolved_config_file = cached_file(
                           ^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/myenv/lib/python3.11/site-packages/transformers/utils/hub.py", line 454, in cached_file
    raise EnvironmentError(
OSError: Incorrect path_or_model_id: 'TheBloke/Mistral-7B-Instruct-v0.2-GGUF/mistral-7b-instruct-v0.2.Q6_K.gguf'. Please provide either the path to a local folder or the repo_id of a model on the Hub.
```

**Comment by davidmezzetti** [comment]
Hello, thank you for the write up. This functionality is coming with the next release of txtai. It can be used now by installing from source. 

```
pip install git+https://github.com/neuml/txtai
```

**Comment by ciekawy** [comment]
Thanks, yup I manage to found that, sorry for the noise :)

**Comment by davidmezzetti** [comment]
No problem, sometimes it's nice to have an easy question once in a while.
