### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by anushakabber** [neuml/txtai#683]
Traceback: 
`ERROR - Traceback (most recent call last):

File "/src/Extraction.py", line 29, in get_text

paragraphs = textractor(filepath)

File "/src/txtai/pipeline/data/segmentation.py", line 68, in __call__

value = self.text(value)

File "/src/txtai/pipeline/data/textractor.py", line 57, in text

return self.extract(text)

File "/src/txtai/pipeline/data/textractor.py", line 117, in __call__

nodes.append(self.process(body))

File "/src/txtai/pipeline/data/textractor.py", line 146, in process

text = "\n".join(self.process(node) for node in children) if self.iscontainer(node, children) else self.text(node)

File "/src/txtai/pipeline/data/textractor.py", line 146, in <genexpr>

text = "\n".join(self.process(node) for node in children) if self.iscontainer(node, children) else self.text(node)

File "/src/txtai/pipeline/data/textractor.py", line 146, in process

text = "\n".join(self.process(node) for node in children) if self.iscontainer(node, children) else self.text(node)

TypeError: 'NoneType' object is not iterable`

The following error is being produced for certain PDFs like the one attached here. The error only showed up after updating from txtai 5.0.0 to 7.0.0. Would greatly appreciate any input on the problem. Please let me know if any further details are required. 
[Costco.pdf](https://github.com/neuml/txtai/files/14490494/Costco.pdf)

**Comment by davidmezzetti** [comment]
If you're open to [installing from source](https://neuml.github.io/txtai/install/#install-from-source), please try the latest fix I just checked in.

**Comment by anushakabber** [comment]
Worked! Thank you!!
