### ISSUE TITLE
AWQ is only available on GPU - no LLM instanciation possible

### ISSUE THREAD

**Issue by redskate** [neuml/txtai#687]
Dear community

Thank you for sharing your interesting code!
I am running ubuntu20 on iMac (2014) using as GPU:
VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Tonga XT / Amethyst XT [Radeon R9 380X / R9 M295X]

with the following I installed
pip3 install torch==2.0.1 torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
and
pip3 install autoawq

Afterwords txtai as you instruct

I am blocked on the instanciation of the LLM
`llm = LLM("TheBloke/Mistral-7B-OpenOrca-AWQ")`

Since my python3 says "valueError: AWQ is only available on GPU" which lets me conclude that my torch be not "talking" with the GPU and hence the LLM cannot load.

How should I solve this in order to properly instanciate an LLM ?

Thanks a lot in advance!

PS: Here the python exception traceback as it comes:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/access/.local/lib/python3.8/site-packages/txtai/pipeline/llm/llm.py", line 34, in __init__
    self.generator = GenerationFactory.create(path, method, **kwargs)
  File "/home/access/.local/lib/python3.8/site-packages/txtai/pipeline/llm/factory.py", line 41, in create
    return HFGeneration(path, **kwargs)
  File "/home/access/.local/lib/python3.8/site-packages/txtai/pipeline/llm/huggingface.py", line 22, in __init__
    self.llm = HFLLM(path, **kwargs)
  File "/home/access/.local/lib/python3.8/site-packages/txtai/pipeline/llm/huggingface.py", line 35, in __init__
    super().__init__(self.task(path, task, **kwargs), path, quantize, gpu, model, **kwargs)
  File "/home/access/.local/lib/python3.8/site-packages/txtai/pipeline/hfpipeline.py", line 56, in __init__
    self.pipeline = pipeline(task, model=path, device=device, model_kwargs=modelargs, **kwargs)
  File "/home/access/.local/lib/python3.8/site-packages/transformers/pipelines/__init__.py", line 905, in pipeline
    framework, model = infer_framework_load_model(
  File "/home/access/.local/lib/python3.8/site-packages/transformers/pipelines/base.py", line 292, in infer_framework_load_model
    raise ValueError(
ValueError: Could not load model TheBloke/Mistral-7B-OpenOrca-AWQ with any of the following classes: (<class 'transformers.models.auto.modeling_auto.AutoModelForCausalLM'>, <class 'transformers.models.mistral.modeling_mistral.MistralForCausalLM'>). See the original errors:

while loading with AutoModelForCausalLM, an error is thrown:
Traceback (most recent call last):
  File "/home/access/.local/lib/python3.8/site-packages/transformers/pipelines/base.py", line 279, in infer_framework_load_model
    model = model_class.from_pretrained(model, **kwargs)
  File "/home/access/.local/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 561, in from_pretrained
    return model_class.from_pretrained(
  File "/home/access/.local/lib/python3.8/site-packages/transformers/modeling_utils.py", line 3014, in from_pretrained
    config.quantization_config = AutoHfQuantizer.merge_quantization_configs(
  File "/home/access/.local/lib/python3.8/site-packages/transformers/quantizers/auto.py", line 145, in merge_quantization_configs
    quantization_config = AutoQuantizationConfig.from_dict(quantization_config)
  File "/home/access/.local/lib/python3.8/site-packages/transformers/quantizers/auto.py", line 75, in from_dict
    return target_cls.from_dict(quantization_config_dict)
  File "/home/access/.local/lib/python3.8/site-packages/transformers/utils/quantization_config.py", line 90, in from_dict
    config = cls(**config_dict)
  File "/home/access/.local/lib/python3.8/site-packages/transformers/utils/quantization_config.py", line 655, in __init__
    self.post_init()
  File "/home/access/.local/lib/python3.8/site-packages/transformers/utils/quantization_config.py", line 662, in post_init
    raise ValueError("AWQ is only available on GPU")
ValueError: AWQ is only available on GPU

while loading with MistralForCausalLM, an error is thrown:
Traceback (most recent call last):
  File "/home/access/.local/lib/python3.8/site-packages/transformers/pipelines/base.py", line 279, in infer_framework_load_model
    model = model_class.from_pretrained(model, **kwargs)
  File "/home/access/.local/lib/python3.8/site-packages/transformers/modeling_utils.py", line 3014, in from_pretrained
    config.quantization_config = AutoHfQuantizer.merge_quantization_configs(
  File "/home/access/.local/lib/python3.8/site-packages/transformers/quantizers/auto.py", line 145, in merge_quantization_configs
    quantization_config = AutoQuantizationConfig.from_dict(quantization_config)
  File "/home/access/.local/lib/python3.8/site-packages/transformers/quantizers/auto.py", line 75, in from_dict
    return target_cls.from_dict(quantization_config_dict)
  File "/home/access/.local/lib/python3.8/site-packages/transformers/utils/quantization_config.py", line 90, in from_dict
    config = cls(**config_dict)
  File "/home/access/.local/lib/python3.8/site-packages/transformers/utils/quantization_config.py", line 655, in __init__
    self.post_init()
  File "/home/access/.local/lib/python3.8/site-packages/transformers/utils/quantization_config.py", line 662, in post_init
    raise ValueError("AWQ is only available on GPU")
ValueError: AWQ is only available on GPU
```

**Comment by davidmezzetti** [comment]
I'd ask this question over on the AutoAWQ project: https://github.com/casper-hansen/AutoAWQ

I'm not sure if this configuration is supported.

**Comment by redskate** [comment]
So I did (https://github.com/casper-hansen/AutoAWQ/issues/416) thank you for this hint.

**Comment by redskate** [comment]
However, when I consider the command where it crashes

 llm = LLM("TheBloke/Mistral-7B-OpenOrca-AWQ")

I do see that this mentions as input a string "TheBloke/Mistral-7B-OpenOrca-AWQ" which suggests that you used a model named "Mistral-7B-OpenOrca-AWQ" ... 

I should not change this (I guess) even if I install anoter GPU)

**Comment by redskate** [comment]
However the prerequisites to autoawq seems to be principally NVIDIA cards of capability >= 7.5

Considering that prerequisite be one NVIDIA GPU of capability of at least 7.5 and that those are

T400
T600
T1000
Quadro RTX 4000
Quadro RTX 5000
Quadro RTX 6000
Quadro RTX 8000

the NVIDIA T400 should hence be "enough" to get autoAWQ to work (even if probably quite slowly)

**Comment by LucisVivae** [comment]
Realise this is closed, but this also solved another error with the AWQ module not being available on my Windows install which nearly had me giving up trying txtai. Thanks for this, txtai looks like the most production focused library in this space.
